apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: quickart
spec:
  type: LoadBalancer
  selector:
    app: user-service
  ports:
    - port: 80
      targetPort: 8081
