apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-service
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: product=prav1619/product-service
    argocd-image-updater.argoproj.io/product.update-strategy: latest
    argocd-image-updater.argoproj.io/product.tag-pattern: "^[0-9a-f]{7}$"
    argocd-image-updater.argoproj.io/write-back-method: git

spec:
  project: default

  source:
    repoURL: https://github.com/<your-org>/Quickart-deploy
    targetRevision: main
    path: charts/quickart
    helm:
      valueFiles:
        - ../../environments/dev/product-service.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: quickart

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
