apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-service
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: product=prav1619/product-service
    argocd-image-updater.argoproj.io/product.update-strategy: name
    argocd-image-updater.argoproj.io/product.tag-pattern: "^[0-9a-f]{7}$"
    argocd-image-updater.argoproj.io/product.write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/product.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/product.helm.image-tag: image.tag

spec:
  project: default

  source:
    repoURL: https://github.com/Prav1619/Quickart-deploy
    targetRevision: main
    path: charts/product-service
    helm:
      valueFiles:
        - ../../environments/dev/product-service.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: quickart

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
