apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Prav1619/Quickart-deploy
    targetRevision: main
    path: charts/user-service

    helm:
      valueFiles:
        - ../../environments/dev/user-service.yaml   # 👈 CRITICAL

  destination:
    server: https://kubernetes.default.svc
    namespace: quickart

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
