replicaCount: 2

image:
  repository: prav1619/product-service   # or user-service
  tag: "latest"

service:
  type: LoadBalancer
  port: 8081
  targetPort: 8081

containerPort: 8081

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"
